@startuml dss-demonstration
skinparam style strictuml
participant ":Chargé laboratoire" as C
participant ":Equipe" as E
participant ":System" as S
participant ":Github" as G

C --> E: demande le début de la démonstration
E --> S: ouvrir application et document d'exigence côte à côte
Loop Tant que le chargé de laboratoin n'est pas satisfait
    C --> E: selectionner cas d'utilisation ou FURPS
    E --> S: demontrer le fonctionnement du scénario principale et alternatif s'il y a leu
    C --> E: identification des problèmes
    E --> G**:  création d'une tâche pour correction
end

@enduml

@startuml dss-evaluation-implementation
skinparam style strictuml
participant ":Chargé laboratoire" as C
participant ":System" as S
participant ":Equipe" as E
participant ":Github" as G

C --> S: ouvrir code et rapport de l'itération
C --> S: vérifier correspondance code vs MDD
Loop Tant que le chargé de laboratoin n'est pas satisfait
    C --> S: selectionner un RDCU
    C --> S: vérifier correspondance code et RDCU
    opt problèmes
        C --> E : information sur le problème à corriger
        E --> G**: création d'une tâche pour correction
    end
end

C -->S: exécuter les tests
opt problèmes
    C --> E : information sur le problème à corriger
    E --> G**: création d'une tâche pour correction
end

@enduml
