@startuml dss-details-demarrerJeu
skinparam style strictuml
skinparam backgroundcolor transparent
skinparam SequenceBoxBorderColor transparent
skinparam participantpadding 10
'skinparam handwritten true
skinparam sequenceMessageAlign center
actor ":Joueur" as j
box "Couche présentation\n(Navigateur + une partie du Serveur)" #ddffdd
participant ":Button" as b <<NavigateurWeb>>
participant ":JeuRouteur" as r <<NodeExpress>>
end box
box "Couche domaine" #ddddff
participant ":JeuDeDés" as c <<ContrôleurGRASP>>
participant "..." as s
end box
j -> b : cliquer
'note over r : Class du serveur web
b ->> r : REST niveau 1\nHTTP GET /api/v1/demarrerJeu/Cris
r ->> r : demarrerJeu\n(req, res)
note right
Express
//router handler//
end note
skinparam NoteTextAlignment center
note over r, c
L'<color blue>**opération système**</color> est envoyée
à un //objet du domaine// (le contrôleur GRASP)
end note
r -[#blue,bold]> c : <color blue><size 20>**demarrerJeu**\n<color blue><size 20>**(nom:String)**</color>
c -> s : ...
note over c, s : Selon la RDCU...
@enduml
