@startuml figureF16.24-web
skinparam style strictuml
skinparam defaultFontName Helvetica,Arial,sans-serif
skinparam backgroundcolor transparent
scale 1
skinparam sequenceMessageAlign center
skinparam participantPadding 10
skinparam sequenceBoxBorderColor transparent
actor ":Joueur" as j
box "Couche présentation" #ddffdd
participant ":Button" as b << NavigateurWeb >> 
participant ":Routeur" as r << NodeExpress >>
end box
box "Couche domaine" #ddddff
participant ":JeuRisk" as c << ContrôleurGRASP >>
participant "..." as s
end box
j -> b : cliquer
b ->> r : HTTP GET\n/api/v1/demarrerJeu/Toto...
note over r : Router handler (Express)
r ->> r : démarrerJeu
note over r, c: Opération système définie dans DSS
r -> c : **<size:18>   démarrerJeu(...)   **
c -> s : ...
note over c, s : selon la RDCU
@enduml