@startuml MDD
skinparam style strictuml
skinparam defaultfontname Verdana
left to right direction
hide empty members
'skinparam linetype ortho
title Modèle du domaine (adapté du Jeu de dés du Ch. 1 de Larman)
class Joueur {
  nom : String
  nbParties : int
  nbPartiesGagnées : int
}
class Dé {
  valeur : int
}
class JeuDeDés

JeuDeDés "1" -- "2" Dé : inclut >
Joueur "*" -l- "1" JeuDeDés : joue >
'Joueur "1" -- "2" Dé : lance >
@enduml