@startuml MDD
skinparam style strictuml
skinparam ArrowThickness 2
skinparam ArrowColor #gray
hide empty members
title Modèle du domaine (adapté du Jeu de dés du Ch. 1 de Larman)
class Joueur {
  nom : String
  nbParties : int
  nbPartiesGagnées : int
}
class Dé {
  valeur : int
}
class JeuDeDés
' associations
Joueur "*" -down- "1" JeuDeDés : joue >
Joueur "1" -right- "2" Dé : lance >
JeuDeDés "1" -up- "2" Dé : inclut >
@enduml