@startuml
skinparam style strictuml
title RDCU pour terminerJeu
participant ":JeuDeDes" as c
participant "j:Joueur" as j
note left of c : par Contrôleur 
->c : terminerJeu(nom)
note right of c : selon Transformer ID en objets 
c->c : j = getJoueur(nom)
c-->j
destroy j
@enduml