@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour démarrerJeu
participant ":JeuDeDes" as c
->c : demarrerJeu(nom)
note right : par Contrôleur
participant "j:Joueur" as j
create j
participant "joueurs:\nMap<Joueur>" as jm
c-->j : j = create(nom)
note right : par Créateur\n(JeuDeDes //agrège// Joueur)
c -> jm : add(j)
note right : selon Expert
@enduml