@startuml
skinparam style strictuml
title RDCU pour démarrerJeu
participant ":JeuDeDes" as c
note left of c : par Créateur\net Contrôleur 
->c : demarrerJeu(nom)
note right of c : JeuDeDes crée Joueur\npar Créateur
participant "j:Joueur" as j
create j
participant "joueurs:\nMap<Joueur>" as jm
c-->j : j = create(nom)
c -> jm : add(j)
@enduml